services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "sleep 5 && php spark migrate && apache2-foreground"

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: _tugas_pemrog_web
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
